lib: [
  "_build/install/default/lib/ppx_reconstuct/META" {"META"}
  "_build/install/default/lib/ppx_reconstuct/opam" {"opam"}
  "_build/install/default/lib/ppx_reconstuct/ppx_reconstuct.cmi" {"ppx_reconstuct.cmi"}
  "_build/install/default/lib/ppx_reconstuct/ppx_reconstuct.cmx" {"ppx_reconstuct.cmx"}
  "_build/install/default/lib/ppx_reconstuct/ppx_reconstuct.cmt" {"ppx_reconstuct.cmt"}
  "_build/install/default/lib/ppx_reconstuct/ppx_reconstuct.re" {"ppx_reconstuct.re"}
  "_build/install/default/lib/ppx_reconstuct/ppx_reconstuct.cma" {"ppx_reconstuct.cma"}
  "_build/install/default/lib/ppx_reconstuct/ppx_reconstuct.cmxa" {"ppx_reconstuct.cmxa"}
  "_build/install/default/lib/ppx_reconstuct/ppx_reconstuct.a" {"ppx_reconstuct.a"}
  "_build/install/default/lib/ppx_reconstuct/ppx_reconstuct.cmxs" {"ppx_reconstuct.cmxs"}
  "_build/install/default/lib/ppx_reconstuct/ppx_reconstuct.dune" {"ppx_reconstuct.dune"}
]
libexec: [
  "_build/install/default/lib/ppx_reconstuct/ppx.exe" {"ppx.exe"}
]
doc: [
  "_build/install/default/doc/ppx_reconstuct/LICENSE"
]
