lib: [
  "_build/install/default/lib/refract/META" {"META"}
  "_build/install/default/lib/refract/opam" {"opam"}
  "_build/install/default/lib/refract/refract.cmi" {"refract.cmi"}
  "_build/install/default/lib/refract/refract.cmx" {"refract.cmx"}
  "_build/install/default/lib/refract/refract.cmt" {"refract.cmt"}
  "_build/install/default/lib/refract/refract.ml-gen" {"refract.ml-gen"}
  "_build/install/default/lib/refract/refract__RefractCommon.cmi" {"refract__RefractCommon.cmi"}
  "_build/install/default/lib/refract/refract__RefractCommon.cmx" {"refract__RefractCommon.cmx"}
  "_build/install/default/lib/refract/refract__RefractCommon.cmt" {"refract__RefractCommon.cmt"}
  "_build/install/default/lib/refract/RefractCommon.re" {"RefractCommon.re"}
  "_build/install/default/lib/refract/refract__Refract_CrossplatString.cmi" {"refract__Refract_CrossplatString.cmi"}
  "_build/install/default/lib/refract/refract__Refract_CrossplatString.cmx" {"refract__Refract_CrossplatString.cmx"}
  "_build/install/default/lib/refract/refract__Refract_CrossplatString.cmt" {"refract__Refract_CrossplatString.cmt"}
  "_build/install/default/lib/refract/Refract_CrossplatString.re" {"Refract_CrossplatString.re"}
  "_build/install/default/lib/refract/refract__Refract_Request.cmi" {"refract__Refract_Request.cmi"}
  "_build/install/default/lib/refract/refract__Refract_Request.cmx" {"refract__Refract_Request.cmx"}
  "_build/install/default/lib/refract/refract__Refract_Request.cmt" {"refract__Refract_Request.cmt"}
  "_build/install/default/lib/refract/Refract_Request.re" {"Refract_Request.re"}
  "_build/install/default/lib/refract/refract__Refract_Response.cmi" {"refract__Refract_Response.cmi"}
  "_build/install/default/lib/refract/refract__Refract_Response.cmx" {"refract__Refract_Response.cmx"}
  "_build/install/default/lib/refract/refract__Refract_Response.cmt" {"refract__Refract_Response.cmt"}
  "_build/install/default/lib/refract/Refract_Response.re" {"Refract_Response.re"}
  "_build/install/default/lib/refract/refract.cma" {"refract.cma"}
  "_build/install/default/lib/refract/refract.cmxa" {"refract.cmxa"}
  "_build/install/default/lib/refract/refract.a" {"refract.a"}
  "_build/install/default/lib/refract/refract.cmxs" {"refract.cmxs"}
  "_build/install/default/lib/refract/refract.dune" {"refract.dune"}
]
bin: [
  "_build/install/default/bin/TestPpx" {"TestPpx"}
  "_build/install/default/bin/CommonTests" {"CommonTests"}
  "_build/install/default/bin/ppx_refract" {"ppx_refract"}
]
doc: [
  "_build/install/default/doc/refract/README.md"
  "_build/install/default/doc/refract/LICENSE"
]
